repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-added-large-files
        args: [ '--maxkb=1024' ]

  - repo: local
    hooks:
      - id: editorconfig-checker
        name: editorconfig-checker
        entry: docker compose run -T --rm editorconfig-checker
        language: system
        pass_filenames: no

      - id: linters-flake8
        name: flake8
        entry: docker compose run -T --rm py-linters flake8 /check/
        language: system
        pass_filenames: no

      - id: linters-mypy
        name: mypy
        entry: docker compose run -T --rm py-linters mypy /check/
        language: system
        pass_filenames: no

      - id: linters-isort
        name: isort-check
        entry: docker compose run -T --rm py-linters isort --check-only --settings-path /opt/linters/pyproject.toml /check/
        language: system
        pass_filenames: yes
        types: [ python ]
