services:

  fastapi:
    build:
      context: .
    image: fastapi_learning:latest
    volumes:
      - ./src:/app/src
      - ./pyproject.toml:/app/pyproject.toml
      - ./poetry.lock:/app/poetry.lock
    ports:
      - 127.0.0.1:8000:8000
    command: uvicorn --reload --log-config ./src/uvicorn_logging_config.yaml
    restart: unless-stopped


  py-linters:
    build:
      context: ./py-linters/
    image: fastapi_learning_py_linters:latest
    volumes:
      - ./py-linters/pyproject.toml:/opt/linters/pyproject.toml
      - ./py-linters/poetry.lock:/opt/linters/poetry.lock
      # mount source code to check a code with linter running inside a container
      - ./src:/check
    command: 'echo Skipped'

  editorconfig-checker:
    image: mstruebing/editorconfig-checker:v3.0.3
    volumes:
      # mount repository top level folder with .editorconfig file and source code to check with editorconfig-checker
      - ./:/check

  test:
    build:
      context: .
    image: fastapi_learning:latest
    volumes:
      - ./src:/app/src
      - ./pyproject.toml:/app/pyproject.toml
      - ./poetry.lock:/app/poetry.lock
      - ./tests:/app/tests
    entrypoint: []
    command: 'echo Skipped'
